### ISSUE TITLE
Setup test suit

### ISSUE THREAD

**Issue by hovsater** [hovsater/vpm#6]
`vpm` should have a test suit. Ideally integrated with a CI server such as [Travis CI](https://travis-ci.org/).

**Comment by scmx** [comment]
Possible ways to integrate with Travis,
https://github.com/sstephenson/bats/pull/24/files
https://github.com/sstephenson/bats/commit/c36ad10d8c4b7f980b2965de5499257de7c07816
https://github.com/duggan/pontoon/blob/master/.travis.yml

**Comment by KevinSjoberg** [comment]
@scmx thanks for this pull request. I completely dropped the ball on merging it. I'm so sorry.

A new verison of vpm is currently being built in Go, see https://github.com/KevinSjoberg/vpm/tree/vpm-go. This pull request is to be outdated with the release of it. Closing.
