### ISSUE TITLE
Error: Permission denied (publickey)

### ISSUE THREAD

**Issue by ghost** [hovsater/vpm#8]
Getting these errors when bootstrap-ing one some or all of the plugins. Any idea what might be the problem? I've already tried removing and recreating ~/.vim/bundle and re-running `vpm bootstrap`.

``` bash
Please make sure you have the correct access rights
and the repository exists.
vpm: `vim-holylight' could not be inserted

Cloning into 'vim-hemisu'...
Permission denied (publickey).
fatal: Could not read from remote repository.
```

Same goes for `vpm insert...`

``` bash
○ → vpm insert tpope/vim-dispatch
Cloning into 'vim-dispatch'...
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
vpm: `vim-dispatch' could not be inserted
```

**Comment by hovsater** [comment]
Hi @usharf! Thanks for reporting this in. At first glance this seems to be an issue with SSH, i.e., GitHub isn't allowing you to pull down the given repositories. Could you perhaps try to pull down the repository from GitHub manually? If that works, please try running `vpm bootstrap` again and if it still fails I will take a closer look at the issue.

**Comment by ghost** [comment]
Yes, it works just fine if I clone manually.

**Comment by scmx** [comment]
@usharf Are you using `git clone git@github.com:tpope/vim-dispatch.git` or `git clone https://github.com/tpope/vim-dispatch.git` ?
vpm uses cloning via ssh (the first one with `git@github.com:...`) which requires you to have ssh keys setup for github https://help.github.com/articles/generating-ssh-keys/

**Comment by hovsater** [comment]
@usharf did you manage to solve the issue?

**Comment by hovsater** [comment]
A new version written in Go is soon to be released. This will default GitHub clones over HTTPS.
